FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

COPY ["Easy travel agent/requirements.txt", "./"]
RUN pip install --no-cache-dir -r requirements.txt

COPY ["Easy travel agent/", "./"]

EXPOSE 8000

CMD ["uvicorn", "app:app", "--host", "::", "--port", "8000"]
