controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

forum_redirect:
    path: /forum
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /social/forum
        permanent: true
